### ISSUE TITLE
Tabbing Sequence in Encumbrance on CharSheet Out of Whack

### ISSUE THREAD

**Issue by THERigilKent** [ronnke/GURPS-4e-FG-Ruleset#1]
Character Sheet | Secondary Characteristics

Your tabbing sequence in the Encumbrance section is all out of whack. Tabbing from Weight None takes you to Move X-Hvy. To do it correctly, you really have to start at the end as each tab seems to go backwards

**Comment by ronnke** [comment]
Fixed
