### ISSUE TITLE
NPC import not working

### ISSUE THREAD

**Issue by THERigilKent** [ronnke/GURPS-4e-FG-Ruleset#14]
Using version 4, I'm getting the following error when I import a NPC and then open it (only to find it blank):

Ruleset Error: windowcontrol: Database type mismatch for control (notes) in windowclass (npc)
Script Error: [string "campaign/scripts/npc.lua"]:28: attempt to index global 'notes' (a nil value)
Script Error: [string "campaign/scripts/npc.lua"]:28: attempt to index global 'notes' (a nil value)

**Comment by ronnke** [comment]
Ensure you are use the GCA exporter found here: https://goo.gl/uznaLA

**Comment by THERigilKent** [comment]
Ah, interesting. Looks like I may have had an older version of those sheets. Once I replaced it and did the export, it appears to have worked.
