### ISSUE TITLE
Request: Add Lvl Option for Adv/Disads?

### ISSUE THREAD

**Issue by THERigilKent** [ronnke/GURPS-4e-FG-Ruleset#6]
Character Sheet | Traits

Is it possible to add a dice roll option (Lvl) on Advantages/Disadvantages for frequency? So, FREX if you have Bad Temper (12 or less), you have a field to input 12 so you can roll it?

**Comment by ronnke** [comment]
Ads/Disads can have too many roll options, as such a single rollable level field may not cover all occasions. The "Others" tab within the "Abilities" section is intended for such purposes. The ads/disads could have the option to expand to reveal a list of rollable components.

Which would better. Keep all the miscellaneous rollable stuff in the "Othes" tab or build in a drop down list of rollable elements for each ad/disad?

**Comment by ronnke** [comment]
This request is currently handed by the "Other" abilities tab.
