### ISSUE TITLE
Importing Characters from GCA

### ISSUE THREAD

**Issue by THERigilKent** [ronnke/GURPS-4e-FG-Ruleset#8]
General | Importing Characters

I tried using the standard import for characters and it didn't work. Am presuming you are aware of this already?

**Comment by ronnke** [comment]
Yes, this known and a WIP.

**Comment by ronnke** [comment]
GCA imports for player characters is working as of release v3.0. NPC imports is still in development.

**Comment by ronnke** [comment]
NPC imports now available.
